### ISSUE TITLE
NPE crash on Milestone view page

### ISSUE THREAD

**Issue by phansier** [AndreySBer/ForkHub#49]
Steps:
Open Milestone view.
Push on "Open Issues"
Filter page opens.
Tap on Milestone chosebox.
App crashes.

Stacktrace:
```
12-23 14:30:07.356 14032-14032/jp.forkhub E/AndroidRuntime: FATAL EXCEPTION: main
                                                            Process: jp.forkhub, PID: 14032
                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
                                                                at com.github.kevinsawicki.wishlist.ViewUpdater.setText(ViewUpdater.java:162)
                                                                at com.github.kevinsawicki.wishlist.TypeAdapter.setText(TypeAdapter.java:140)
                                                                at com.github.mobile.ui.issue.MilestoneDialogFragment$MilestoneListAdapter.update(MilestoneDialogFragment.java:73)
                                                                at com.github.mobile.ui.issue.MilestoneDialogFragment$MilestoneListAdapter.update(MilestoneDialogFragment.java:48)
                                                                at com.github.kevinsawicki.wishlist.SingleTypeAdapter.update(SingleTypeAdapter.java:164)
                                                                at com.github.kevinsawicki.wishlist.SingleTypeAdapter.getView(SingleTypeAdapter.java:180)
                                                                at android.widget.AbsListView.obtainView(AbsListView.java:3250)
                                                                at android.widget.ListView.measureHeightOfChildren(ListView.java:1396)
                                                                at android.widget.ListView.onMeasure(ListView.java:1303)
                                                                at android.view.View.measure(View.java:21121)
                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6462)
                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                at android.view.View.measure(View.java:21121)
                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6462)
                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                at android.view.View.measure(View.java:21121)
                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6462)
                                                                at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                at android.view.View.measure(View.java:21121)
                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6462)
                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                at android.view.View.measure(View.java:21121)
                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6462)
                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                at android.view.View.measure(View.java:21121)
                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6462)
                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                at com.android.internal.policy.DecorView.onMeasure(DecorView.java:872)
                                                                at android.view.View.measure(View.java:21121)
                                                                at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2625)
                                                                at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1650)
                                                                at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1928)
                                                                at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1550)
                                                                at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:734)
                                                                at android.view.Choreographer.doFrame(Choreographer.java:670)
                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:154)
                                                                at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

**Comment by Motoaleks** [comment]
moved into #52
