### ISSUE TITLE
NPE crush on Issue create page

### ISSUE THREAD

**Issue by Motoaleks** [AndreySBer/ForkHub#51]
Steps:
1. Open repository view
2. Push issues tab
3. Push plus on top-left to add new issue
4. Tap select milestone. => crush

StackTrace:
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: jp.forkhub, PID: 5085
                  java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.CompoundButton.setChecked(boolean)' on a null object reference
                      at com.github.kevinsawicki.wishlist.ViewUpdater.setChecked(ViewUpdater.java:304)
                      at com.github.kevinsawicki.wishlist.TypeAdapter.setChecked(TypeAdapter.java:268)
                      at com.github.mobile.ui.issue.MilestoneDialogFragment$MilestoneListAdapter.update(MilestoneDialogFragment.java:77)
                      at com.github.mobile.ui.issue.MilestoneDialogFragment$MilestoneListAdapter.update(MilestoneDialogFragment.java:48)
                      at com.github.kevinsawicki.wishlist.SingleTypeAdapter.update(SingleTypeAdapter.java:164)
                      at com.github.kevinsawicki.wishlist.SingleTypeAdapter.getView(SingleTypeAdapter.java:180)
                      at android.widget.AbsListView.obtainView(AbsListView.java:2363)
                      at android.widget.ListView.measureHeightOfChildren(ListView.java:1326)
                      at android.widget.ListView.onMeasure(ListView.java:1233)
                      at android.view.View.measure(View.java:19857)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                      at android.view.View.measure(View.java:19857)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                      at android.view.View.measure(View.java:19857)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                      at android.view.View.measure(View.java:19857)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                      at android.view.View.measure(View.java:19857)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                      at android.view.View.measure(View.java:19857)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                      at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
                      at android.view.View.measure(View.java:19857)
                      at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
                      at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                      at android.view.Choreographer.doFrame(Choreographer.java:621)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by Motoaleks** [comment]
moved into #52
